files:
  - source: /sources
    ignore:
      - /sources/logs.txt
      - /sources/db_backup.csv
    translation: /translation/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        uk: ua
