files:
  - source: resources/strings/desktop
    translation: /translations/%two_letters_code%/%original_file_name%
    translate_content: '0'
    translate_attributes: '0'
    content_segmentation: '0'
